FROM rust:1.44.0-slim-buster AS test-build
WORKDIR /test-build
RUN apt-get update && apt-get install -y jq
COPY . .
ENV BUILD_ARTIFACTS=test_artifacts.json
RUN cargo build --tests --message-format=json > ${BUILD_ARTIFACTS}
RUN mv $(jq 'select(.target.name=="db_test") | select(.filenames[0] != null) | .executable' ${BUILD_ARTIFACTS} | xargs) db_test.cargo.bin