DROP TABLE IF EXISTS refinery_schema_history CASCADE;
DROP TABLE IF EXISTS partitions CASCADE;
DROP TABLE IF EXISTS datasets CASCADE;
DROP TABLE IF EXISTS managers CASCADE;
DROP TYPE IF EXISTS compression_t CASCADE;
DROP TYPE IF EXISTS encoding_t CASCADE;
DROP TYPE IF EXISTS classification_t CASCADE;
DROP FUNCTION IF EXISTS on_update_set_timestamp CASCADE;
-- DROP EXTENSION IF EXISTS hstore CASCADE;