DROP TABLE IF EXISTS refinery_schema_history;
DROP TABLE IF EXISTS partitions;
DROP TABLE IF EXISTS datasets;
DROP TABLE IF EXISTS managers;
DROP TYPE IF EXISTS compression_t;
DROP TYPE IF EXISTS encoding_t;
DROP TYPE IF EXISTS classification_t;
DROP FUNCTION IF EXISTS on_update_set_timestamp;
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;